src/oscar_wagtail/urls.py
from django.conf.urls import url

from oscar_wagtail import views

app_name = 'oscar_wagtail'

urlpatterns = [
    url(r'^product-choose/$',
        views.product_choose, name='product_choose'),

    url(r'^product-choose/(\d+)/$',
        views.product_chosen, name='product_chosen'),
]

src/oscar_wagtail/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel
from wagtail.core.models import Orderable
from wagtail.snippets.models import register_snippet

from oscar_wagtail.edit_handlers import ProductChooserPanel


class ProductListSnippet(ClusterableModel):
    title = models.CharField(max_length=255)
    code = models.CharField(max_length=100, unique=True)

    panels = [
        FieldPanel('title'),
        FieldPanel('code'),
    ]

    def __unicode__(self):
        return self.title


class ProductListItem(Orderable):
    parent = ParentalKey(to=ProductListSnippet, related_name='items')
    product = models.ForeignKey('catalogue.Product', related_name='+', on_delete=models.CASCADE)

    panels = [
        ProductChooserPanel('product'),
    ]


ProductListSnippet.panels += [
    InlinePanel('items', label=_("Products"))
]


register_snippet(ProductListSnippet)

src/oscar_wagtail/views.py
import json
from six import text_type

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.urls import reverse
from django.db.models import Q
from django.shortcuts import get_object_or_404
from oscar.core.loading import get_model
from wagtail.admin.forms.search import SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow

Product = get_model('catalogue', 'Product')


def product_choose(request):

    queryset = (
        Product.objects.get_queryset()
        .browsable()
        .order_by('title')
    )

    p = request.GET.get('p', 1)

    if request.GET.get('q'):
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            cleaned_data = searchform.cleaned_data

            if hasattr(queryset, 'search'):
                queryset = queryset.search(cleaned_data['q'])
            else:
                queryset = queryset.filter(
                    Q(title__icontains=cleaned_data['q']) |
                    Q(upc__icontains=cleaned_data['q']))

    else:
        searchform = SearchForm()

    paginator = Paginator(queryset, 10)

    try:
        paginated_items = paginator.page(p)
    except PageNotAnInteger:
        paginated_items = paginator.page(1)
    except EmptyPage:
        paginated_items = paginator.page(paginator.num_pages)

    return render_modal_workflow(
        request,
        'oscar_wagtail/chooser/product_choose.html',
        'oscar_wagtail/chooser/product_choose.js',
        {
            'items': paginated_items,
            'searchform': searchform,
        }
    )


def product_chosen(request, pk):
    product = get_object_or_404(Product, pk=pk)

    product_json = json.dumps({
        'id': product.pk,
        'string': text_type(product),
        'edit_link': reverse(
            'dashboard:catalogue-product', kwargs={'pk': product.pk})
    })

    return render_modal_workflow(
        request,
        None, 'oscar_wagtail/chooser/product_chosen.js',
        {
            'product_json': product_json,
        }
    )

src/oscar_wagtail/templates/oscar_wagtail/blocks/product.html
{% load product_tags %}
{{ product }}

src/oscar_wagtail/templates/oscar_wagtail/chooser/product_choose.html
{% load i18n %}
{% trans "Choose a product" as choose_str %}
{% include "wagtailadmin/shared/header.html" with title=choose_str subtitle=snippet_type_name icon="snippet" %}

    <section id="search" class="active nice-padding">
        <form class="product-search search-bar" action="{% url 'oscar_wagtail:product_choose' %}" method="GET" autocomplete="off">
            <ul class="fields">
                {% for field in searchform %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endfor %}
                <li class="submit"><input type="submit" value="{% trans 'Search' %}" /></li>
            </ul>
        </form>
        <div id="product-results">
    	    {% include "oscar_wagtail/chooser/product_results.html" with choosing=1 %}
        </div>
    </section>

src/oscar_wagtail/templates/oscar_wagtail/chooser/product_results.html
{% load i18n %}

{% url "oscar_wagtail:product_choose" as linkurl %}

<table class="listing" id="product-chooser-list" data-url="{{ linkurl }}">
    <col />
    <col  />
    <col width="16%" />
    <thead>
        <tr class="table-headers">
            <th>{% trans "Title" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for product in items %}
            <tr>
                <td class="title">
                    {% if choosing %}
                        <h2><a class="product-choice" href="{% url 'oscar_wagtail:product_chosen' product.pk %}">{{ product }}</a></h2>
                    {% else %}
                        <h2><a href="{% url 'dashboard:catalogue-product' product.pk %}">{{ product }}</a></h2>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% include "wagtailadmin/shared/pagination_nav.html" with items=items is_ajax=1 %}

src/oscar_wagtail/templates/oscar_wagtail/widgets/product_chooser.html
{% extends "wagtailadmin/widgets/chooser.html" %}
{% load thumbnail %}

{% block chooser_class %}product-chooser{% endblock %}

{% block chosen_state_view %}
    <div class="title">{{ product.get_title }}</div>
    {% if product.primary_image %}
    <div class="image">
        {% with image=product.primary_image %}
            {% thumbnail image.original "x155" upscale=False as thumb %}
            <img src="{{ thumb.url }}" alt="{{ product.get_title }}" class="thumbnail">
            {% endthumbnail %}
        {% endwith %}
    </div>
    {% endif %}
{% endblock %}

{% block edit_chosen_item_url %}{% if product %}{% url 'dashboard:catalogue-product' product.id %}{% endif %}{% endblock %}